### ISSUE TITLE
Database name

### ISSUE THREAD

**Issue by laksa19** [osians/FLATDBase#1]
How to allow database name with numbers?

**Comment by osians** [comment]
> How to allow database name with numbers?

Well, for security reasons the numbers are removed from the name at the time you create a new database.

So, if for some reason you need to change this behavior, look at the file: fdbcripto.class.php

locate the method: make_safe

and at line 19, you can see the follow code:
$value = self::remove_numbers( $value );

if you need, just change it.

**Comment by laksa19** [comment]
Thank you so much :+1:
